insert into 50ndva.cn_region (id, name, region_code) values (1, 'Guadeloupe', '01');
insert into 50ndva.cn_region (id, name, region_code) values (2, 'Martinique', '02');
insert into 50ndva.cn_region (id, name, region_code) values (3, 'Guyane', '03');
insert into 50ndva.cn_region (id, name, region_code) values (4, 'La Réunion', '04');
insert into 50ndva.cn_region (id, name, region_code) values (5, 'Mayotte', '06');
insert into 50ndva.cn_region (id, name, region_code) values (6, 'Île-de-France', '11');
insert into 50ndva.cn_region (id, name, region_code) values (7, 'Centre-Val de Loire', '24');
insert into 50ndva.cn_region (id, name, region_code) values (8, 'Bourgogne-Franche-Comté', '27');
insert into 50ndva.cn_region (id, name, region_code) values (9, 'Normandie', '28');
insert into 50ndva.cn_region (id, name, region_code) values (10, 'Hauts-de-France', '32');
insert into 50ndva.cn_region (id, name, region_code) values (11, 'Grand Est', '44');
insert into 50ndva.cn_region (id, name, region_code) values (12, 'Pays de la Loire', '52');
insert into 50ndva.cn_region (id, name, region_code) values (13, 'Bretagne', '53');
insert into 50ndva.cn_region (id, name, region_code) values (14, 'Nouvelle-Aquitaine', '75');
insert into 50ndva.cn_region (id, name, region_code) values (15, 'Occitanie', '76');
insert into 50ndva.cn_region (id, name, region_code) values (16, 'Auvergne-Rhône-Alpes', '84');
insert into 50ndva.cn_region (id, name, region_code) values (17, 'Provence-Alpes-Côte d''Azur', '93');
insert into 50ndva.cn_region (id, name, region_code) values (18, 'Corse', '94');
insert into 50ndva.cn_region (id, name, region_code) values (19, 'Guadeloupe', '01');
insert into 50ndva.cn_region (id, name, region_code) values (20, 'Martinique', '02');
insert into 50ndva.cn_region (id, name, region_code) values (21, 'Guyane', '03');
insert into 50ndva.cn_region (id, name, region_code) values (22, 'La Réunion', '04');
insert into 50ndva.cn_region (id, name, region_code) values (23, 'Mayotte', '06');
insert into 50ndva.cn_region (id, name, region_code) values (24, 'Île-de-France', '11');
insert into 50ndva.cn_region (id, name, region_code) values (25, 'Centre-Val de Loire', '24');
insert into 50ndva.cn_region (id, name, region_code) values (26, 'Bourgogne-Franche-Comté', '27');
insert into 50ndva.cn_region (id, name, region_code) values (27, 'Normandie', '28');
insert into 50ndva.cn_region (id, name, region_code) values (28, 'Hauts-de-France', '32');
insert into 50ndva.cn_region (id, name, region_code) values (29, 'Grand Est', '44');
insert into 50ndva.cn_region (id, name, region_code) values (30, 'Pays de la Loire', '52');
insert into 50ndva.cn_region (id, name, region_code) values (31, 'Bretagne', '53');
insert into 50ndva.cn_region (id, name, region_code) values (32, 'Nouvelle-Aquitaine', '75');
insert into 50ndva.cn_region (id, name, region_code) values (33, 'Occitanie', '76');
insert into 50ndva.cn_region (id, name, region_code) values (34, 'Auvergne-Rhône-Alpes', '84');
insert into 50ndva.cn_region (id, name, region_code) values (35, 'Provence-Alpes-Côte d''Azur', '93');
insert into 50ndva.cn_region (id, name, region_code) values (36, 'Corse', '94');
insert into 50ndva.cn_region (id, name, region_code) values (37, 'Guadeloupe', '01');
insert into 50ndva.cn_region (id, name, region_code) values (38, 'Martinique', '02');
insert into 50ndva.cn_region (id, name, region_code) values (39, 'Guyane', '03');
insert into 50ndva.cn_region (id, name, region_code) values (40, 'La Réunion', '04');
insert into 50ndva.cn_region (id, name, region_code) values (41, 'Mayotte', '06');
insert into 50ndva.cn_region (id, name, region_code) values (42, 'Île-de-France', '11');
insert into 50ndva.cn_region (id, name, region_code) values (43, 'Centre-Val de Loire', '24');
insert into 50ndva.cn_region (id, name, region_code) values (44, 'Bourgogne-Franche-Comté', '27');
insert into 50ndva.cn_region (id, name, region_code) values (45, 'Normandie', '28');
insert into 50ndva.cn_region (id, name, region_code) values (46, 'Hauts-de-France', '32');
insert into 50ndva.cn_region (id, name, region_code) values (47, 'Grand Est', '44');
insert into 50ndva.cn_region (id, name, region_code) values (48, 'Pays de la Loire', '52');
insert into 50ndva.cn_region (id, name, region_code) values (49, 'Bretagne', '53');
insert into 50ndva.cn_region (id, name, region_code) values (50, 'Nouvelle-Aquitaine', '75');
insert into 50ndva.cn_region (id, name, region_code) values (51, 'Occitanie', '76');
insert into 50ndva.cn_region (id, name, region_code) values (52, 'Auvergne-Rhône-Alpes', '84');
insert into 50ndva.cn_region (id, name, region_code) values (53, 'Provence-Alpes-Côte d''Azur', '93');
insert into 50ndva.cn_region (id, name, region_code) values (54, 'Corse', '94');
